//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.27 at 10:56:29 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com/samples/webservices/userService", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.springws.service.jaxb;
